/// Flutter code sample for BottomNavigationBar

// This example shows a [BottomNavigationBar] as it is used within a [Scaffold]
// widget. The [BottomNavigationBar] has three [BottomNavigationBarItem]
// widgets, which means it defaults to [BottomNavigationBarType.fixed], and
// the [currentIndex] is set to index 0. The selected item is
// amber. The `_onItemTapped` function changes the selected item's index
// and displays a corresponding message in the center of the [Scaffold].

import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';

/// This is the main application widget.

/// This is the stateful widget that the main application instantiates.
class TermsScreen extends StatefulWidget {
  const TermsScreen({Key key}) : super(key: key);
  @override
  State<TermsScreen> createState() => _TermsScreene();
}

/// This is the private State class that goes with MyStatefulWidget.
class _TermsScreene extends State<TermsScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: Text('Terms and Conditions',
              style: TextStyle(color: Colors.green[900]))),
      body: SingleChildScrollView(
          child: Html(
            data: """
<p style='margin-top:0in;margin-right:0in;margin-bottom:4.5pt;margin-left:0in;line-height:12.0pt;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:13px;font-family:Roboto;color:#263238;">Privacy Policy</span></strong><span style="font-size:13px;font-family:Roboto;color:#263238;"><br>&nbsp;EV HUB built the EV HUB app as an Open Source app. This SERVICE is provided by EV HUB at no cost and is intended for use as is.<br>&nbsp;This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.<br>&nbsp;If you choose to use our Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.<br>&nbsp;The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at EV HUB unless otherwise defined in this Privacy Policy.<br> <strong>Information Collection and Use</strong><br>&nbsp;For a better experience, while using our Service, we may require you to provide us with certain personally identifiable information. The information that we request will be retained by us and used as described in this privacy policy.<br>&nbsp;The app does use third party services that may collect information used to identify you.<br>&nbsp;Link to privacy policy of third party service providers used by the app<br>&nbsp;&bull; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Google Play Services<br>&nbsp;&bull; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Google Analytics for Firebase<br>&nbsp;&bull; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Firebase Crashlytics<br> <strong>Log Data</strong><br>&nbsp;We want to inform you that whenever you use our Service, in a case of an error in the app we collect data and information (through third party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (&ldquo;IP&rdquo;) address, device name, operating system version, the configuration of the app when utilizing our Service, the time and date of your use of the Service, and other statistics.<br> <strong>Cookies</strong><br>&nbsp;Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device&apos;s internal memory.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:4.5pt;margin-left:0in;line-height:12.0pt;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:13px;font-family:Roboto;color:#263238;">&nbsp; &nbsp; &nbsp; This Service does not use these &ldquo;cookies&rdquo; explicitly. However, the app may use third party code and libraries that use &ldquo;cookies&rdquo; to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.<br> <strong>Service Providers</strong><br>&nbsp;We may employ third-party companies and individuals due to the following reasons:<br>&nbsp;To facilitate our Service;<br>&nbsp;To provide the Service on our behalf;<br>&nbsp;To perform Service-related services; or<br>&nbsp;To assist us in analyzing how our Service is used.<br>&nbsp;We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.<br> <strong>Security</strong><br>&nbsp;We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.<br> <strong>Links to Other Sites</strong><br>&nbsp;This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.<br> <strong>Children&rsquo;s Privacy</strong></span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:4.5pt;margin-left:0in;line-height:12.0pt;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:13px;font-family:Roboto;color:#263238;">&nbsp; &nbsp; &nbsp; These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13 years of age. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.<br> <strong>Changes to This Privacy Policy</strong><br>&nbsp;We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page.<br>&nbsp;This policy is effective as of 2021-05-26<br> <strong>Contact Us</strong><br> If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at <a href="mailto:pinanaleepile@gmail.com" target="_blank"><span style="color:#263238;">pinanaleepile@gmail.com</span></a>.<br>&nbsp;This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:4.5pt;margin-left:0in;line-height:12.0pt;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:13px;font-family:Roboto;color:#263238;">&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:4.5pt;margin-left:0in;line-height:12.0pt;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:13px;font-family:Roboto;color:#263238;">Terms &amp; Conditions</span></strong><span style="font-size:13px;font-family:Roboto;color:#263238;"><br>&nbsp;By downloading or using the app, these terms will automatically apply to you &ndash; you should make sure therefore that you read them carefully before using the app. You&rsquo;re not allowed to copy, or modify the app, any part of the app, or our trademarks in any way. You&rsquo;re not allowed to attempt to extract the source code of the app, and you also shouldn&rsquo;t try to translate the app into other languages, or make derivative versions. The app itself, and all the trade marks, copyright, database rights and other intellectual property rights related to it, still belong to EV HUB.<br>&nbsp;EV HUB is committed to ensuring that the app is as useful and efficient as possible. For that reason, we reserve the right to make changes to the app or to charge for its services, at any time and for any reason. We will never charge you for the app or its services without making it very clear to you exactly what you&rsquo;re paying for.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:4.5pt;margin-left:0in;line-height:12.0pt;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:13px;font-family:Roboto;color:#263238;">&nbsp; &nbsp; &nbsp; The EV HUB app stores and processes personal data that you have provided to us, in order to provide our Service. It&rsquo;s your responsibility to keep your phone and access to the app secure. We therefore recommend that you do not jailbreak or root your phone, which is the process of removing software restrictions and limitations imposed by the official operating system of your device. It could make your phone vulnerable to malware/viruses/malicious programs, compromise your phone&rsquo;s security features and it could mean that the EV HUB app won&rsquo;t work properly or at all.<br>&nbsp;The app does use third party services that declare their own Terms and Conditions.<br>&nbsp;Link to Terms and Conditions of third party service providers used by the app<br>&nbsp;Google Play Services<br>&nbsp;Google Analytics for Firebase<br>&nbsp;Firebase Crashlytics<br>&nbsp;You should be aware that there are certain things that EV HUB will not take responsibility for. Certain functions of the app will require the app to have an active internet connection. The connection can be Wi-Fi, or provided by your mobile network provider, but EV HUB cannot take responsibility for the app not working at full functionality if you don&rsquo;t have access to Wi-Fi, and you don&rsquo;t have any of your data allowance left.<br>&nbsp;<br>&nbsp;If you&rsquo;re using the app outside of an area with Wi-Fi, you should remember that your terms of the agreement with your mobile network provider will still apply. As a result, you may be charged by your mobile provider for the cost of data for the duration of the connection while accessing the app, or other third party charges. In using the app, you&rsquo;re accepting responsibility for any such charges, including roaming data charges if you use the app outside of your home territory (i.e. region or country) without turning off data roaming. If you are not the bill payer for the device on which you&rsquo;re using the app, please be aware that we assume that you have received permission from the bill payer for using the app.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:4.5pt;margin-left:0in;line-height:12.0pt;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:13px;font-family:Roboto;color:#263238;">&nbsp; &nbsp; &nbsp; At some point, we may wish to update the app. The app is currently available on &ndash; the requirements for system(and for any additional systems we decide to extend the availability of the app to) may change, and you&rsquo;ll need to download the updates if you want to keep using the app. EV HUB does not promise that it will always update the app so that it is relevant to you and/or works with the version that you have installed on your device. However, you promise to always accept updates to the application when offered to you, We may also wish to stop providing the app, and may terminate use of it at any time without giving notice of termination to you. Unless we tell you otherwise, upon any termination, (a) the rights and licenses granted to you in these terms will end; (b) you must stop using the app, and (if needed) delete it from your device.<br> <strong>Changes to This Terms and Conditions</strong><br>&nbsp;We may update our Terms and Conditions from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Terms and Conditions on this page.<br>&nbsp;These terms and conditions are effective as of 2021-05-26<br> <strong>Contact Us</strong><br> If you have any questions or suggestions about our Terms and Conditions, do not hesitate to contact us at <a href="mailto:pinanaleepile@gmail.com" target="_blank"><span style="color:#263238;">pinanaleepile@gmail.com</span></a>.<br>&nbsp;This Terms and Conditions page was generated by App Privacy Policy Generato</span></p>""",
            padding: EdgeInsets.all(20),
          ),
        )
    );
  }
}
